package planning.controller;

import planning.model.Calendrier;
import planning.model.dates.* ;
import planning.view.PanelCalendrier;

public class PlanningController extends javax.swing.JPanel {

    Annee t;
    Mois m;
    Calendrier c;
    PanelCalendrier panelCalendrier;

    public PlanningController(PanelCalendrier panelCalendrier) {
        this.panelCalendrier = panelCalendrier;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        anneeLabel = new javax.swing.JLabel();
        anneeTextField = new javax.swing.JTextField();
        moisLabel = new javax.swing.JLabel();
        semaineLabel = new javax.swing.JLabel();
        confirmerButton = new javax.swing.JButton();
        semaineComboBox = new javax.swing.JComboBox();
        moisComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contrôleur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 13), new java.awt.Color(51, 51, 255))); // NOI18N

        anneeLabel.setText("Année : ");
        anneeLabel.setToolTipText("");

        anneeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeTextFieldActionPerformed(evt);
            }
        });

        moisLabel.setText("Mois : ");

        semaineLabel.setText("Semaine : ");

        confirmerButton.setText("Confirmer");
        confirmerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerButtonActionPerformed(evt);
            }
        });

        semaineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        semaineComboBox.setSelectedItem(semaineComboBox);

        moisComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, moisComboBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), moisComboBox, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moisLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(anneeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anneeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(moisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(semaineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semaineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(confirmerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anneeTextField, moisComboBox, semaineComboBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anneeLabel)
                    .addComponent(anneeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moisLabel))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semaineLabel)
                    .addComponent(semaineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {anneeLabel, anneeTextField, moisComboBox, moisLabel});

        anneeLabel.getAccessibleContext().setAccessibleName("Année :");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void anneeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeTextFieldActionPerformed


    }//GEN-LAST:event_anneeTextFieldActionPerformed

    private void confirmerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerButtonActionPerformed
        int a = Integer.parseInt(anneeTextField.getText());
        // System.out.println("REGARDE ICI ON RENTRE DANS LA METHODE RAIIII !");
        if (this.panelCalendrier != null) {
            this.panelCalendrier.getModele().getDates().clear();
        }
        int mois;
        mois = Integer.parseInt(moisComboBox.getSelectedItem().toString());
        int semaine;
        semaine = Integer.parseInt(semaineComboBox.getSelectedItem().toString());
        Date d = new Date();
        d.setAnnee(a);
        d.setMois(d.associerMois(mois));
        c = new Calendrier(d);
        c.listeDates(this.panelCalendrier.getModele(), semaine);

        //  System.out.println("on affiche l'adresse de l'objet t dans la methode bouton " + t);
        // t.DateMois(mois, semaine);
        //il faudrait créer les dates ici ?

    }//GEN-LAST:event_confirmerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anneeLabel;
    private javax.swing.JTextField anneeTextField;
    private javax.swing.JButton confirmerButton;
    private javax.swing.JComboBox moisComboBox;
    private javax.swing.JLabel moisLabel;
    private javax.swing.JComboBox semaineComboBox;
    private javax.swing.JLabel semaineLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
